CREATE DATABASE gamestorrentanywhere CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE gamestorrentanywhere;

CREATE TABLE users(
    ID int AUTO_INCREMENT,
    USERNAME varchar(50) NOT NULL,
    PASSWORD varchar(64) NOT NULL,
    ROLE int(2) NOT NULL DEFAULT 3,
    REGISTRATION_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOGIN_DATE DATETIME,
    PRIMARY KEY(ID)
);

CREATE TABLE games(
    ID int AUTO_INCREMENT,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    TYPE int,
    FORMAT TEXT,
    PLATFORM TEXT,
    GENRE TEXT,
    DEVELOPER TEXT,
    PUBLISHER TEXT,
    SIZE TEXT,
    VERSION TEXT,
    UPLOADER TEXT,
    EXT_IMG_URL TEXT,
    INT_IMG_URL varchar(500),
    TRAILER_URL TEXT,
    RELEASED_AT DATETIME,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    USER_ID int DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE game_files(
    ID int AUTO_INCREMENT,
    MAGNET_FILE_ROUTE TEXT,
    EXT_FILE_ROUTE_1 TEXT,
    INT_FILE_ROUTE varchar(500),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    GAME_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES games(ID)
);

CREATE TABLE game_genres(
    ID int AUTO_INCREMENT,
    GENRE TEXT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    GAME_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES games(ID)
);

CREATE TABLE game_languages(
    ID int AUTO_INCREMENT,
    LANGUAGE TEXT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    GAME_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES games(ID)
);

CREATE TABLE ad_urls(
    ID int AUTO_INCREMENT,
    AD_URL_1 TEXT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    GAME_FILE_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_FILE_ID) REFERENCES game_files(ID)
);